name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: kushagrasaxena061/photo-ai-backend:${{ github.sha }}
      
      - name: Clone staging-ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/kushagrasaxena061/staging-ops.git
          cd staging-ops
          sed -i 's|image: kushagrasaxena061/photo-ai-backend:.*|image: kushagrasaxena061/photo-ai-backend:${{ github.sha }}|' prod/photo-ai/deployment.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add prod/photo-ai/deployment.yml
          git commit -m "Update dailycode image to ${{ github.sha }}"
          git push https://${PAT}@github.com/kushagrasaxena061/staging-ops.git main